apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: $NAMESPACE
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: al_hardy@live.com.au
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
