apiVersion: apps/v1
kind: Deployment
metadata:
  name: values-backend-deployment
  namespace: $NAMESPACE
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      ms: values
      apptype: worker
      aadpodidbinding: values-microservice-identity-binding
  template:
    metadata:
      labels:
        tier: backend
        ms: values
        apptype: worker
        aadpodidbinding: values-microservice-identity-binding
    spec:
      containers:
        - name: values-backend
          image: $ACR_NAME.azurecr.io/values-backend:latest
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "96Mi"
              cpu: "0.2"
